package com.powernode.crm.settings.mapper;

import com.powernode.crm.settings.model.DicValue;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Jul 24 18:48:14 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Jul 24 18:48:14 CST 2023
     */
    int insert(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Jul 24 18:48:14 CST 2023
     */
    int insertSelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Jul 24 18:48:14 CST 2023
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Jul 24 18:48:14 CST 2023
     */
    int updateByPrimaryKeySelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Jul 24 18:48:14 CST 2023
     */
    int updateByPrimaryKey(DicValue row);

    /**
     * 根据数据字典类型获取数据字典值
     */
    List<DicValue> selectDicValueByDicTypeCode(String typeCode);
}